/*
 * Generated by Abacus.
 */
package com.landawn.samples.abacus.entity;

import java.sql.Timestamp;
import java.util.List;

import com.landawn.abacus.annotation.Type;
import com.landawn.abacus.util.N;

/**
 * Generated by Abacus.
 * @version ${version}
 */
public class Account {
    private long id;
    private String gui;
    private String emailAddress;
    private String firstName;
    private String middleName;
    private String lastName;
    private Timestamp birthDate;
    private int status;
    private Timestamp lastUpdateTime;
    private Timestamp createTime;
    private Contact contact;
    private List<Device> devices;

    public Account() {
    }

    public Account(long id) {
        this();

        setId(id);
    }

    public Account(String gui, String emailAddress, String firstName, String middleName, String lastName, Timestamp birthDate, int status,
            Timestamp lastUpdateTime, Timestamp createTime, Contact contact, List<Device> devices) {
        this();

        setGUI(gui);
        setEmailAddress(emailAddress);
        setFirstName(firstName);
        setMiddleName(middleName);
        setLastName(lastName);
        setBirthDate(birthDate);
        setStatus(status);
        setLastUpdateTime(lastUpdateTime);
        setCreateTime(createTime);
        setContact(contact);
        setDevices(devices);
    }

    public Account(long id, String gui, String emailAddress, String firstName, String middleName, String lastName, Timestamp birthDate, int status,
            Timestamp lastUpdateTime, Timestamp createTime, Contact contact, List<Device> devices) {
        this();

        setId(id);
        setGUI(gui);
        setEmailAddress(emailAddress);
        setFirstName(firstName);
        setMiddleName(middleName);
        setLastName(lastName);
        setBirthDate(birthDate);
        setStatus(status);
        setLastUpdateTime(lastUpdateTime);
        setCreateTime(createTime);
        setContact(contact);
        setDevices(devices);
    }

    @Type("long")
    public long getId() {
        return id;
    }

    public Account setId(long id) {
        this.id = id;

        return this;
    }

    @Type("String")
    public String getGUI() {
        return gui;
    }

    public Account setGUI(String gui) {
        this.gui = gui;

        return this;
    }

    @Type("String")
    public String getEmailAddress() {
        return emailAddress;
    }

    public Account setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;

        return this;
    }

    @Type("String")
    public String getFirstName() {
        return firstName;
    }

    public Account setFirstName(String firstName) {
        this.firstName = firstName;

        return this;
    }

    @Type("String")
    public String getMiddleName() {
        return middleName;
    }

    public Account setMiddleName(String middleName) {
        this.middleName = middleName;

        return this;
    }

    @Type("String")
    public String getLastName() {
        return lastName;
    }

    public Account setLastName(String lastName) {
        this.lastName = lastName;

        return this;
    }

    @Type("Timestamp")
    public Timestamp getBirthDate() {
        return birthDate;
    }

    public Account setBirthDate(Timestamp birthDate) {
        this.birthDate = birthDate;

        return this;
    }

    @Type("int")
    public int getStatus() {
        return status;
    }

    public Account setStatus(int status) {
        this.status = status;

        return this;
    }

    @Type("Timestamp")
    public Timestamp getLastUpdateTime() {
        return lastUpdateTime;
    }

    public Account setLastUpdateTime(Timestamp lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;

        return this;
    }

    @Type("Timestamp")
    public Timestamp getCreateTime() {
        return createTime;
    }

    public Account setCreateTime(Timestamp createTime) {
        this.createTime = createTime;

        return this;
    }

    @Type("com.landawn.samples.abacus.entity.Contact")
    public Contact getContact() {
        return contact;
    }

    public Account setContact(Contact contact) {
        this.contact = contact;

        return this;
    }

    @Type("com.landawn.samples.abacus.entity.Device>")
    public List<Device> getDevices() {
        return devices;
    }

    public Account setDevices(List<Device> devices) {
        this.devices = devices;

        return this;
    }

    @Override
    public int hashCode() {
        int h = 17;
        h = 31 * h + N.hashCode(id);
        h = 31 * h + N.hashCode(gui);
        h = 31 * h + N.hashCode(emailAddress);
        h = 31 * h + N.hashCode(firstName);
        h = 31 * h + N.hashCode(middleName);
        h = 31 * h + N.hashCode(lastName);
        h = 31 * h + N.hashCode(birthDate);
        h = 31 * h + N.hashCode(status);
        h = 31 * h + N.hashCode(lastUpdateTime);
        h = 31 * h + N.hashCode(createTime);
        h = 31 * h + N.hashCode(contact);
        h = 31 * h + N.hashCode(devices);

        return h;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj instanceof Account) {
            final Account other = (Account) obj;

            return N.equals(id, other.id) && N.equals(gui, other.gui) && N.equals(emailAddress, other.emailAddress) && N.equals(firstName, other.firstName)
                    && N.equals(middleName, other.middleName) && N.equals(lastName, other.lastName) && N.equals(birthDate, other.birthDate)
                    && N.equals(status, other.status) && N.equals(lastUpdateTime, other.lastUpdateTime) && N.equals(createTime, other.createTime)
                    && N.equals(contact, other.contact) && N.equals(devices, other.devices);
        }

        return false;
    }

    @Override
    public String toString() {
        return "{id=" + N.toString(id) + ", gui=" + N.toString(gui) + ", emailAddress=" + N.toString(emailAddress) + ", firstName=" + N.toString(firstName)
                + ", middleName=" + N.toString(middleName) + ", lastName=" + N.toString(lastName) + ", birthDate=" + N.toString(birthDate) + ", status="
                + N.toString(status) + ", lastUpdateTime=" + N.toString(lastUpdateTime) + ", createTime=" + N.toString(createTime) + ", contact="
                + N.toString(contact) + ", devices=" + N.toString(devices) + "}";
    }
}
