/*
 * Generated by Abacus.
 */
package com.landawn.samples.abacus.entity;

import java.sql.Timestamp;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Contact {
    private long id;
    private long accountId;
    private String mobile;
    private String telephone;
    private String email;
    private String address;
    private String address2;
    private String city;
    private String state;
    private String country;
    private String zipCode;
    private String category;
    private String description;
    private int status;
    private Timestamp lastUpdateTime;
    private Timestamp createTime;
}
