/*
 * Generated by Abacus.
 */
package com.landawn.samples.abacus.entity;

import java.sql.Timestamp;
import com.landawn.abacus.util.N;
import com.landawn.abacus.annotation.Type;


/**
 * Generated by Abacus.
 * @version ${version}
 */
public class Device {
    private long id;
    private long accountId;
    private String name;
    private String udid;
    private String platform;
    private String model;
    private String manufacturer;
    private Timestamp produceTime;
    private String category;
    private String description;
    private int status;
    private Timestamp lastUpdateTime;
    private Timestamp createTime;

    public Device() {
    }

    public Device(long id) {
        this();

        setId(id);
    }

    public Device(long accountId, String name, String udid, String platform, 
        String model, String manufacturer, Timestamp produceTime, 
        String category, String description, int status, 
        Timestamp lastUpdateTime, Timestamp createTime) {
        this();

        setAccountId(accountId);
        setName(name);
        setUDID(udid);
        setPlatform(platform);
        setModel(model);
        setManufacturer(manufacturer);
        setProduceTime(produceTime);
        setCategory(category);
        setDescription(description);
        setStatus(status);
        setLastUpdateTime(lastUpdateTime);
        setCreateTime(createTime);
    }

    public Device(long id, long accountId, String name, String udid, String platform, 
        String model, String manufacturer, Timestamp produceTime, 
        String category, String description, int status, 
        Timestamp lastUpdateTime, Timestamp createTime) {
        this();

        setId(id);
        setAccountId(accountId);
        setName(name);
        setUDID(udid);
        setPlatform(platform);
        setModel(model);
        setManufacturer(manufacturer);
        setProduceTime(produceTime);
        setCategory(category);
        setDescription(description);
        setStatus(status);
        setLastUpdateTime(lastUpdateTime);
        setCreateTime(createTime);
    }

    @Type("long")
    public long getId() {
        return id;
    }

    public Device setId(long id) {
        this.id = id;

        return this;
    }

    @Type("long")
    public long getAccountId() {
        return accountId;
    }

    public Device setAccountId(long accountId) {
        this.accountId = accountId;

        return this;
    }

    @Type("String")
    public String getName() {
        return name;
    }

    public Device setName(String name) {
        this.name = name;

        return this;
    }

    @Type("String")
    public String getUDID() {
        return udid;
    }

    public Device setUDID(String udid) {
        this.udid = udid;

        return this;
    }

    @Type("String")
    public String getPlatform() {
        return platform;
    }

    public Device setPlatform(String platform) {
        this.platform = platform;

        return this;
    }

    @Type("String")
    public String getModel() {
        return model;
    }

    public Device setModel(String model) {
        this.model = model;

        return this;
    }

    @Type("String")
    public String getManufacturer() {
        return manufacturer;
    }

    public Device setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;

        return this;
    }

    @Type("Timestamp")
    public Timestamp getProduceTime() {
        return produceTime;
    }

    public Device setProduceTime(Timestamp produceTime) {
        this.produceTime = produceTime;

        return this;
    }

    @Type("String")
    public String getCategory() {
        return category;
    }

    public Device setCategory(String category) {
        this.category = category;

        return this;
    }

    @Type("String")
    public String getDescription() {
        return description;
    }

    public Device setDescription(String description) {
        this.description = description;

        return this;
    }

    @Type("int")
    public int getStatus() {
        return status;
    }

    public Device setStatus(int status) {
        this.status = status;

        return this;
    }

    @Type("Timestamp")
    public Timestamp getLastUpdateTime() {
        return lastUpdateTime;
    }

    public Device setLastUpdateTime(Timestamp lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;

        return this;
    }

    @Type("Timestamp")
    public Timestamp getCreateTime() {
        return createTime;
    }

    public Device setCreateTime(Timestamp createTime) {
        this.createTime = createTime;

        return this;
    }

    public int hashCode() {
        int h = 17;
        h = 31 * h + N.hashCode(id);
        h = 31 * h + N.hashCode(accountId);
        h = 31 * h + N.hashCode(name);
        h = 31 * h + N.hashCode(udid);
        h = 31 * h + N.hashCode(platform);
        h = 31 * h + N.hashCode(model);
        h = 31 * h + N.hashCode(manufacturer);
        h = 31 * h + N.hashCode(produceTime);
        h = 31 * h + N.hashCode(category);
        h = 31 * h + N.hashCode(description);
        h = 31 * h + N.hashCode(status);
        h = 31 * h + N.hashCode(lastUpdateTime);
        h = 31 * h + N.hashCode(createTime);

        return h;
    }

    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj instanceof Device) {
            final Device other = (Device) obj;

            return N.equals(id, other.id)
                && N.equals(accountId, other.accountId)
                && N.equals(name, other.name)
                && N.equals(udid, other.udid)
                && N.equals(platform, other.platform)
                && N.equals(model, other.model)
                && N.equals(manufacturer, other.manufacturer)
                && N.equals(produceTime, other.produceTime)
                && N.equals(category, other.category)
                && N.equals(description, other.description)
                && N.equals(status, other.status)
                && N.equals(lastUpdateTime, other.lastUpdateTime)
                && N.equals(createTime, other.createTime);
        }

        return false;
    }

    public String toString() {
         return "{id=" + N.toString(id)
                 + ", accountId=" + N.toString(accountId)
                 + ", name=" + N.toString(name)
                 + ", udid=" + N.toString(udid)
                 + ", platform=" + N.toString(platform)
                 + ", model=" + N.toString(model)
                 + ", manufacturer=" + N.toString(manufacturer)
                 + ", produceTime=" + N.toString(produceTime)
                 + ", category=" + N.toString(category)
                 + ", description=" + N.toString(description)
                 + ", status=" + N.toString(status)
                 + ", lastUpdateTime=" + N.toString(lastUpdateTime)
                 + ", createTime=" + N.toString(createTime)
                 + "}";
    }
}
