/*
 * Generated by Abacus.
 */
package com.landawn.abacus.test.entity;

import java.sql.Timestamp;
import com.landawn.abacus.util.N;


/**
 * Generated by Abacus. DO NOT edit it!
 * @version ${version}
 */
public class AccountDevice {
    private long id;
    private long accountId;
    private String name;
    private String udid;
    private String platform;
    private String model;
    private String manufacturer;
    private Timestamp produceTime;
    private String category;
    private String description;
    private int status;
    private Timestamp lastUpdateTime;
    private Timestamp createTime;

    public AccountDevice() {
    }

    public AccountDevice(long id) {
        this();

        setId(id);
    }

    public AccountDevice(long accountId, String name, String udid, String platform, 
        String model, String manufacturer, Timestamp produceTime, 
        String category, String description, int status, 
        Timestamp lastUpdateTime, Timestamp createTime) {
        this();

        setAccountId(accountId);
        setName(name);
        setUDID(udid);
        setPlatform(platform);
        setModel(model);
        setManufacturer(manufacturer);
        setProduceTime(produceTime);
        setCategory(category);
        setDescription(description);
        setStatus(status);
        setLastUpdateTime(lastUpdateTime);
        setCreateTime(createTime);
    }

    public AccountDevice(long id, long accountId, String name, String udid, String platform, 
        String model, String manufacturer, Timestamp produceTime, 
        String category, String description, int status, 
        Timestamp lastUpdateTime, Timestamp createTime) {
        this();

        setId(id);
        setAccountId(accountId);
        setName(name);
        setUDID(udid);
        setPlatform(platform);
        setModel(model);
        setManufacturer(manufacturer);
        setProduceTime(produceTime);
        setCategory(category);
        setDescription(description);
        setStatus(status);
        setLastUpdateTime(lastUpdateTime);
        setCreateTime(createTime);
    }

    public long getId() {
        return id;
    }

    public AccountDevice setId(long id) {
        this.id = id;

        return this;
    }

    public long getAccountId() {
        return accountId;
    }

    public AccountDevice setAccountId(long accountId) {
        this.accountId = accountId;

        return this;
    }

    public String getName() {
        return name;
    }

    public AccountDevice setName(String name) {
        this.name = name;

        return this;
    }

    public String getUDID() {
        return udid;
    }

    public AccountDevice setUDID(String udid) {
        this.udid = udid;

        return this;
    }

    public String getPlatform() {
        return platform;
    }

    public AccountDevice setPlatform(String platform) {
        this.platform = platform;

        return this;
    }

    public String getModel() {
        return model;
    }

    public AccountDevice setModel(String model) {
        this.model = model;

        return this;
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public AccountDevice setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;

        return this;
    }

    public Timestamp getProduceTime() {
        return produceTime;
    }

    public AccountDevice setProduceTime(Timestamp produceTime) {
        this.produceTime = produceTime;

        return this;
    }

    public String getCategory() {
        return category;
    }

    public AccountDevice setCategory(String category) {
        this.category = category;

        return this;
    }

    public String getDescription() {
        return description;
    }

    public AccountDevice setDescription(String description) {
        this.description = description;

        return this;
    }

    public int getStatus() {
        return status;
    }

    public AccountDevice setStatus(int status) {
        this.status = status;

        return this;
    }

    public Timestamp getLastUpdateTime() {
        return lastUpdateTime;
    }

    public AccountDevice setLastUpdateTime(Timestamp lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;

        return this;
    }

    public Timestamp getCreateTime() {
        return createTime;
    }

    public AccountDevice setCreateTime(Timestamp createTime) {
        this.createTime = createTime;

        return this;
    }

    public AccountDevice copy() {
        AccountDevice copy = new AccountDevice();

        copy.id = this.id;
        copy.accountId = this.accountId;
        copy.name = this.name;
        copy.udid = this.udid;
        copy.platform = this.platform;
        copy.model = this.model;
        copy.manufacturer = this.manufacturer;
        copy.produceTime = this.produceTime;
        copy.category = this.category;
        copy.description = this.description;
        copy.status = this.status;
        copy.lastUpdateTime = this.lastUpdateTime;
        copy.createTime = this.createTime;

        return copy;
    }

    public int hashCode() {
        int h = 17;
        h = 31 * h + N.hashCode(id);
        h = 31 * h + N.hashCode(accountId);
        h = 31 * h + N.hashCode(name);
        h = 31 * h + N.hashCode(udid);
        h = 31 * h + N.hashCode(platform);
        h = 31 * h + N.hashCode(model);
        h = 31 * h + N.hashCode(manufacturer);
        h = 31 * h + N.hashCode(produceTime);
        h = 31 * h + N.hashCode(category);
        h = 31 * h + N.hashCode(description);
        h = 31 * h + N.hashCode(status);
        h = 31 * h + N.hashCode(lastUpdateTime);
        h = 31 * h + N.hashCode(createTime);

        return h;
    }

    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj instanceof AccountDevice) {
            AccountDevice other = (AccountDevice) obj;

            if (N.equals(id, other.id)
                && N.equals(accountId, other.accountId)
                && N.equals(name, other.name)
                && N.equals(udid, other.udid)
                && N.equals(platform, other.platform)
                && N.equals(model, other.model)
                && N.equals(manufacturer, other.manufacturer)
                && N.equals(produceTime, other.produceTime)
                && N.equals(category, other.category)
                && N.equals(description, other.description)
                && N.equals(status, other.status)
                && N.equals(lastUpdateTime, other.lastUpdateTime)
                && N.equals(createTime, other.createTime)) {

                return true;
            }
        }

        return false;
    }

    public String toString() {
        return "{"
                 + "id=" + N.toString(id) + ", "
                 + "accountId=" + N.toString(accountId) + ", "
                 + "name=" + N.toString(name) + ", "
                 + "udid=" + N.toString(udid) + ", "
                 + "platform=" + N.toString(platform) + ", "
                 + "model=" + N.toString(model) + ", "
                 + "manufacturer=" + N.toString(manufacturer) + ", "
                 + "produceTime=" + N.toString(produceTime) + ", "
                 + "category=" + N.toString(category) + ", "
                 + "description=" + N.toString(description) + ", "
                 + "status=" + N.toString(status) + ", "
                 + "lastUpdateTime=" + N.toString(lastUpdateTime) + ", "
                 + "createTime=" + N.toString(createTime)
                 + "}";
    }
}