/*
 * Generated by Abacus.
 */
package com.landawn.abacus.entity;

import java.util.List;
import java.util.Map;
import com.landawn.abacus.util.BiMap;

import com.landawn.abacus.util.N;


/**
 * Generated by Abacus. DO NOT edit it!
 * @version ${version}
 */
public interface CodesCNL {
    public static final String _DN = "codes".intern();

    public static interface LoginCNL {
        /**
         * Name of "login" table. 
         */
        public static final String _ = "login".intern();

        /**
         * Name of "id" column. 
         * Java type: long. 
         */
        public static final String ID = (_ + ".id").intern();

        /**
         * Name of "account_id" column. 
         * Java type: long. 
         */
        public static final String ACCOUNT_ID = (_ + ".account_id").intern();

        /**
         * Name of "login_id" column. 
         * Java type: String. 
         */
        public static final String LOGIN_ID = (_ + ".login_id").intern();

        /**
         * Name of "login_password" column. 
         * Java type: String. 
         */
        public static final String LOGIN_PASSWORD = (_ + ".login_password").intern();

        /**
         * Name of "status" column. 
         * Java type: int. 
         */
        public static final String STATUS = (_ + ".status").intern();

        /**
         * Name of "last_update_time" column. 
         * Java type: Timestamp. 
         */
        public static final String LAST_UPDATE_TIME = (_ + ".last_update_time").intern();

        /**
         * Name of "create_time" column. 
         * Java type: Timestamp. 
         */
        public static final String CREATE_TIME = (_ + ".create_time").intern();

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = N.asUnmodifiableList(ID, ACCOUNT_ID, LOGIN_ID, LOGIN_PASSWORD, STATUS, LAST_UPDATE_TIME, CREATE_TIME);

        /**
         * Immutable column name to tableName.columnName mapper
         */
         @SuppressWarnings("rawtypes")
        public static final BiMap<String, String> _CNM = N.asUnmodifiableBiMapForInterface((Map)N.asLinkedHashMap(ID, "id".intern(), ACCOUNT_ID, "account_id".intern(), LOGIN_ID, "login_id".intern(), LOGIN_PASSWORD, "login_password".intern(), STATUS, "status".intern(), LAST_UPDATE_TIME, "last_update_time".intern(), CREATE_TIME, "create_time".intern()));

        /**
         * Immutable column name to property name mapper
         */
         @SuppressWarnings("rawtypes")
        public static final BiMap<String, String> _CPM = N.asUnmodifiableBiMapForInterface((Map)N.asLinkedHashMap(ID, "Login.id".intern(), ACCOUNT_ID, "Login.accountId".intern(), LOGIN_ID, "Login.loginId".intern(), LOGIN_PASSWORD, "Login.loginPassword".intern(), STATUS, "Login.status".intern(), LAST_UPDATE_TIME, "Login.lastUpdateTime".intern(), CREATE_TIME, "Login.createTime".intern()));

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = N.asUnmodifiableList("Login.id".intern(), "Login.accountId".intern(), "Login.loginId".intern(), "Login.loginPassword".intern(), "Login.status".intern(), "Login.lastUpdateTime".intern(), "Login.createTime".intern());

        /**
         * Immutable property name to entityName.propName mapper
         */
         @SuppressWarnings("rawtypes")
        public static final BiMap<String, String> _PNM = N.asUnmodifiableBiMapForInterface((Map)N.asLinkedHashMap("Login.id".intern(), "id".intern(), "Login.accountId".intern(), "accountId".intern(), "Login.loginId".intern(), "loginId".intern(), "Login.loginPassword".intern(), "loginPassword".intern(), "Login.status".intern(), "status".intern(), "Login.lastUpdateTime".intern(), "lastUpdateTime".intern(), "Login.createTime".intern(), "createTime".intern()));
    }

    public static interface AccountDeviceCNL {
        /**
         * Name of "account_device" table. 
         */
        public static final String _ = "account_device".intern();

        /**
         * Name of "id" column. 
         * Java type: long. 
         */
        public static final String ID = (_ + ".id").intern();

        /**
         * Name of "account_id" column. 
         * Java type: long. 
         */
        public static final String ACCOUNT_ID = (_ + ".account_id").intern();

        /**
         * Name of "name" column. 
         * Java type: String. 
         */
        public static final String NAME = (_ + ".name").intern();

        /**
         * Name of "udid" column. 
         * Java type: String. 
         */
        public static final String UDID = (_ + ".udid").intern();

        /**
         * Name of "platform" column. 
         * Java type: String. 
         */
        public static final String PLATFORM = (_ + ".platform").intern();

        /**
         * Name of "model" column. 
         * Java type: String. 
         */
        public static final String MODEL = (_ + ".model").intern();

        /**
         * Name of "manufacturer" column. 
         * Java type: String. 
         */
        public static final String MANUFACTURER = (_ + ".manufacturer").intern();

        /**
         * Name of "produce_time" column. 
         * Java type: Timestamp. 
         */
        public static final String PRODUCE_TIME = (_ + ".produce_time").intern();

        /**
         * Name of "category" column. 
         * Java type: String. 
         */
        public static final String CATEGORY = (_ + ".category").intern();

        /**
         * Name of "description" column. 
         * Java type: String. 
         */
        public static final String DESCRIPTION = (_ + ".description").intern();

        /**
         * Name of "status" column. 
         * Java type: int. 
         */
        public static final String STATUS = (_ + ".status").intern();

        /**
         * Name of "last_update_time" column. 
         * Java type: Timestamp. 
         */
        public static final String LAST_UPDATE_TIME = (_ + ".last_update_time").intern();

        /**
         * Name of "create_time" column. 
         * Java type: Timestamp. 
         */
        public static final String CREATE_TIME = (_ + ".create_time").intern();

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = N.asUnmodifiableList(ID, ACCOUNT_ID, NAME, UDID, PLATFORM, MODEL, MANUFACTURER, PRODUCE_TIME, CATEGORY, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME);

        /**
         * Immutable column name to tableName.columnName mapper
         */
         @SuppressWarnings("rawtypes")
        public static final BiMap<String, String> _CNM = N.asUnmodifiableBiMapForInterface((Map)N.asLinkedHashMap(ID, "id".intern(), ACCOUNT_ID, "account_id".intern(), NAME, "name".intern(), UDID, "udid".intern(), PLATFORM, "platform".intern(), MODEL, "model".intern(), MANUFACTURER, "manufacturer".intern(), PRODUCE_TIME, "produce_time".intern(), CATEGORY, "category".intern(), DESCRIPTION, "description".intern(), STATUS, "status".intern(), LAST_UPDATE_TIME, "last_update_time".intern(), CREATE_TIME, "create_time".intern()));

        /**
         * Immutable column name to property name mapper
         */
         @SuppressWarnings("rawtypes")
        public static final BiMap<String, String> _CPM = N.asUnmodifiableBiMapForInterface((Map)N.asLinkedHashMap(ID, "AccountDevice.id".intern(), ACCOUNT_ID, "AccountDevice.accountId".intern(), NAME, "AccountDevice.name".intern(), UDID, "AccountDevice.UDID".intern(), PLATFORM, "AccountDevice.platform".intern(), MODEL, "AccountDevice.model".intern(), MANUFACTURER, "AccountDevice.manufacturer".intern(), PRODUCE_TIME, "AccountDevice.produceTime".intern(), CATEGORY, "AccountDevice.category".intern(), DESCRIPTION, "AccountDevice.description".intern(), STATUS, "AccountDevice.status".intern(), LAST_UPDATE_TIME, "AccountDevice.lastUpdateTime".intern(), CREATE_TIME, "AccountDevice.createTime".intern()));

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = N.asUnmodifiableList("AccountDevice.id".intern(), "AccountDevice.accountId".intern(), "AccountDevice.name".intern(), "AccountDevice.UDID".intern(), "AccountDevice.platform".intern(), "AccountDevice.model".intern(), "AccountDevice.manufacturer".intern(), "AccountDevice.produceTime".intern(), "AccountDevice.category".intern(), "AccountDevice.description".intern(), "AccountDevice.status".intern(), "AccountDevice.lastUpdateTime".intern(), "AccountDevice.createTime".intern());

        /**
         * Immutable property name to entityName.propName mapper
         */
         @SuppressWarnings("rawtypes")
        public static final BiMap<String, String> _PNM = N.asUnmodifiableBiMapForInterface((Map)N.asLinkedHashMap("AccountDevice.id".intern(), "id".intern(), "AccountDevice.accountId".intern(), "accountId".intern(), "AccountDevice.name".intern(), "name".intern(), "AccountDevice.UDID".intern(), "UDID".intern(), "AccountDevice.platform".intern(), "platform".intern(), "AccountDevice.model".intern(), "model".intern(), "AccountDevice.manufacturer".intern(), "manufacturer".intern(), "AccountDevice.produceTime".intern(), "produceTime".intern(), "AccountDevice.category".intern(), "category".intern(), "AccountDevice.description".intern(), "description".intern(), "AccountDevice.status".intern(), "status".intern(), "AccountDevice.lastUpdateTime".intern(), "lastUpdateTime".intern(), "AccountDevice.createTime".intern(), "createTime".intern()));
    }

    public static interface AccountCNL {
        /**
         * Name of "account" table. 
         */
        public static final String _ = "account".intern();

        /**
         * Name of "id" column. 
         * Java type: long. 
         */
        public static final String ID = (_ + ".id").intern();

        /**
         * Name of "gui" column. 
         * Java type: String. 
         */
        public static final String GUI = (_ + ".gui").intern();

        /**
         * Name of "first_name" column. 
         * Java type: String. 
         */
        public static final String FIRST_NAME = (_ + ".first_name").intern();

        /**
         * Name of "last_name" column. 
         * Java type: String. 
         */
        public static final String LAST_NAME = (_ + ".last_name").intern();

        /**
         * Name of "status" column. 
         * Java type: int. 
         */
        public static final String STATUS = (_ + ".status").intern();

        /**
         * Name of "last_update_time" column. 
         * Java type: Timestamp. 
         */
        public static final String LAST_UPDATE_TIME = (_ + ".last_update_time").intern();

        /**
         * Name of "create_time" column. 
         * Java type: Timestamp. 
         */
        public static final String CREATE_TIME = (_ + ".create_time").intern();

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = N.asUnmodifiableList(ID, GUI, FIRST_NAME, LAST_NAME, STATUS, LAST_UPDATE_TIME, CREATE_TIME);

        /**
         * Immutable column name to tableName.columnName mapper
         */
         @SuppressWarnings("rawtypes")
        public static final BiMap<String, String> _CNM = N.asUnmodifiableBiMapForInterface((Map)N.asLinkedHashMap(ID, "id".intern(), GUI, "gui".intern(), FIRST_NAME, "first_name".intern(), LAST_NAME, "last_name".intern(), STATUS, "status".intern(), LAST_UPDATE_TIME, "last_update_time".intern(), CREATE_TIME, "create_time".intern()));

        /**
         * Immutable column name to property name mapper
         */
         @SuppressWarnings("rawtypes")
        public static final BiMap<String, String> _CPM = N.asUnmodifiableBiMapForInterface((Map)N.asLinkedHashMap(ID, "Account.id".intern(), GUI, "Account.gui".intern(), FIRST_NAME, "Account.firstName".intern(), LAST_NAME, "Account.lastName".intern(), STATUS, "Account.status".intern(), LAST_UPDATE_TIME, "Account.lastUpdateTime".intern(), CREATE_TIME, "Account.createTime".intern()));

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = N.asUnmodifiableList("Account.id".intern(), "Account.gui".intern(), "Account.firstName".intern(), "Account.lastName".intern(), "Account.status".intern(), "Account.lastUpdateTime".intern(), "Account.createTime".intern());

        /**
         * Immutable property name to entityName.propName mapper
         */
         @SuppressWarnings("rawtypes")
        public static final BiMap<String, String> _PNM = N.asUnmodifiableBiMapForInterface((Map)N.asLinkedHashMap("Account.id".intern(), "id".intern(), "Account.gui".intern(), "gui".intern(), "Account.firstName".intern(), "firstName".intern(), "Account.lastName".intern(), "lastName".intern(), "Account.status".intern(), "status".intern(), "Account.lastUpdateTime".intern(), "lastUpdateTime".intern(), "Account.createTime".intern(), "createTime".intern()));
    }

    public static final String ACCOUNT_ID = "account_id".intern();

    public static final String CATEGORY = "category".intern();

    public static final String CREATE_TIME = "create_time".intern();

    public static final String DESCRIPTION = "description".intern();

    public static final String FIRST_NAME = "first_name".intern();

    public static final String GUI = "gui".intern();

    public static final String ID = "id".intern();

    public static final String LAST_NAME = "last_name".intern();

    public static final String LAST_UPDATE_TIME = "last_update_time".intern();

    public static final String LOGIN_ID = "login_id".intern();

    public static final String LOGIN_PASSWORD = "login_password".intern();

    public static final String MANUFACTURER = "manufacturer".intern();

    public static final String MODEL = "model".intern();

    public static final String NAME = "name".intern();

    public static final String PLATFORM = "platform".intern();

    public static final String PRODUCE_TIME = "produce_time".intern();

    public static final String STATUS = "status".intern();

    public static final String UDID = "udid".intern();

    /**
     * Mapping of column name to property name 
     */
     @SuppressWarnings("rawtypes")
    public static final BiMap<String, String> _CPM = N.asUnmodifiableBiMapForInterface((Map) N.asLinkedHashMap(ACCOUNT_ID, "accountId".intern(), CATEGORY, "category".intern(), CREATE_TIME, "createTime".intern(), DESCRIPTION, "description".intern(), FIRST_NAME, "firstName".intern(), GUI, "gui".intern(), ID, "id".intern(), LAST_NAME, "lastName".intern(), LAST_UPDATE_TIME, "lastUpdateTime".intern(), LOGIN_ID, "loginId".intern(), LOGIN_PASSWORD, "loginPassword".intern(), MANUFACTURER, "manufacturer".intern(), MODEL, "model".intern(), NAME, "name".intern(), PLATFORM, "platform".intern(), PRODUCE_TIME, "produceTime".intern(), STATUS, "status".intern(), UDID, "UDID".intern()));
}
