/*
 * Generated by Abacus.
 */
package com.landawn.abacus.entity;


/**
 * Generated by Abacus. DO NOT edit it!
 * @version ${version}
 */
public final class CodesSQLMapperIdList {
    public static final String INSERT_ACCOUNT = "insertAccount";
    public static final String SELECT_ACCOUNT_BY_ID = "selectAccountById";
    public static final String SELECT_ALL_ACCOUNT = "selectAllAccount";
    public static final String UPDATE_ACCOUNT_FIRST_NAME_BY_ID = "updateAccountFirstNameById";
    public static final String DELETE_ACCOUNT_BY_ID = "deleteAccountById";
    public static final String DELETE_ALL_ACCOUNT = "deleteAllAccount";
}
